---
name: 25rerun-lowlr
nclasses: 4

data_prefix: post
batch_size: 6
training_scales: [1.]
training_resolution: 1024
eval_resolution: 1024

segmentation_arch: Unet
attention: scse
amp_opt_level: O1
aug_prob: 0.25
encoder: efficientnet-b3
lr: 0.0002 #0.0005
optim: adam
scheduler_factor: 0.1
scheduler_patience: 5
epochs: 100
filter_none: True
mode: categorical
metric: "building:f1"

add_suppl: False
add_tertiary: False
train_repeat: 1

class_weight: [1,3,2,2]
loss_reduce_mode: "mean"

project: sky-eye-full
freeze_encoder_norm: False
freeze_decoder_norm: False
load_weights: False
sync_bn: True
train_patch: False
n_cpus: 10
