--- 
name: FPN-eb2-batch6
nclasses: 4

data_prefix: post
batch_size: 6
training_scales: [1.]
training_resolution: 1024
eval_resolution: 1024

segmentation_arch: FPN
decoder_segmentation_channels: 128
decoder_pyramid_channels: 256


amp_opt_level: O1
aug_prob: 0.4
encoder: efficientnet-b2
loss_weights: {ce: 1} #, focal: 4}
class_weight: [1,3,2,2]
lr: 0.0005 #0.0005
optim: adam
scheduler_factor: 0.2
scheduler_patience: 5
epochs: 100
filter_none: True
mode: categorical
metric: "hmean:damage:categorical:f1"
loss_reduce_mode: mean

add_suppl: False
add_tertiary: False
train_repeat: 1

project: building-seg-damage
freeze_encoder_norm: False
freeze_decoder_norm: False
load_weights: False
sync_bn: True
train_patch: False
n_cpus: 10
