--- 
nclasses: 4
data_prefix: post
run_name: building_damage
batch_size: 6
aug_prob: 0.5
training_scales: [1.]
loss_weights: {ce: 1}
lr: 0.000005
optim: adam
scheduler_factor: 0.5
scheduler_patience: 5
epochs: 100
metric: "hmean:damage:categorical:f1"
backbone: resnet101
filter_none: True
class_weight: [1, 3, 2, 2]
loss_reduce_mode: "sum"
min_bbox_visibility: 0.2
add_suppl: False
train_repeat: 2
pretrain_weights: False #'/home/jupyter/sky-eye/notebooks/wandb/run-20191106_084154-35ipugq1/final_state_dict.pth'
