--- 
nclasses: 4
data_prefix: post
name: highdrop
batch_size: 6
min_bbox_visibility: 0.2

training_scales: [1., 1., .75]
aug_prob: 0.25
resolution: 1024
filter_none: True

loss_weights: {ce: 1}
lr: 0.0002
optim: adam
scheduler_factor: 0.2
scheduler_patience: 3
epochs: 50

metric: "hmean:damage:categorical:f1"
class_weight: [1, 3, 2, 2]
loss_reduce_mode: "mean"

pretrain_weights: False
add_suppl: False
train_repeat: 1

amp_opt_level: O1

freeze_backbone_norm: False
freeze_model_norm: False
convert_groupnorm: False

model_params:
    encoder_name: efficientnet-b2
    nclasses: 4
    features: [3,2,1,0]
    out_channels: 256
    dropout: 0.5
    representation_size: 1024
    use_bifpn: False
