--- 
nclasses: 4
data_prefix: post
run_name: building_damage
batch_size: 4
amp_opt_level: O1
aug_prob: 0.5
training_scales: [1.]
loss_weights: {dicemulti: 1}
lr: 0.00001
optim: adam
scheduler_factor: 0.5
scheduler_patience: 5
epochs: 100
metric: "hmean:damage:categorical:f1"
backbone: resnet101
filter_none: True
class_weight: [1, 3, 2, 2]
min_bbox_visibility: 0.2
add_suppl: True
train_repeat: 1
pretrain_weights: False
