---
name: reconf-restart
nclasses: 1

data_prefix: pre
batch_size: 4
training_scales: [1.]
training_resolution: 512
eval_resolution: 1024

segmentation_arch: Unet
attention: scse
amp_opt_level: O1
aug_prob: 0.5
encoder: efficientnet-b6
loss_weights: {jaccard: 1, focal: 4}
lr: 0.00001 #0.0005
optim: adam
scheduler_factor: 0.5
scheduler_patience: 5
epochs: 100
filter_none: False
mode: null
metric: "building:f1"

add_suppl: False
train_repeat: 1
add_tertiary: False

project: sky-eye-full
freeze_encoder_norm: False
freeze_decoder_norm: False
load_weights: '/home/jupyter/sky-eye/notebooks/wandb/run-20191122_035516-ph4c64ar/state_dict.pth'
sync_bn: True
train_patch: True
n_cpus: 10