---
nclasses: 1
data_prefix: pre
segmentation_arch: Unet
attention: scse
batch_size: 1
training_scales: [.75, 1.]
training_resolution: 1024
amp_opt_level: O0
aug_prob: 0.5
encoder: efficientnet-b7
loss_weights: {jaccard: 1, focal: 4}
lr: 0.000005
optim: adam
scheduler_factor: 0.5
scheduler_patience: 5
epochs: 100
filter_none: False
mode: dual
in_channels: 6
metric: "building:f1"
add_suppl: False
train_repeat: 1
project: sky-eye-full
freeze_encoder_norm: True
freeze_decoder_norm: True
load_weights: './wandb/run-20191114_230343-k78iuzql/state_dict.pth'