--- 
name: FPN-dual
nclasses: 4

data_prefix: post
batch_size: 3
training_scales: [1.]
training_resolution: 1024
eval_resolution: 1024

segmentation_arch: FPN
decoder_segmentation_channels: 96
decoder_pyramid_channels: 64
decoder_merge_policy: add

# attention_type: scse


mode: categorical
dual_input: True
dual_head_channels: 64

amp_opt_level: O1
aug_prob: 0.4
encoder: efficientnet-b0
loss_weights: {ce: 1} #, focal: 4}
class_weight: [1,3,2,2]
lr: 0.0005 #0.0005
optim: adam
scheduler_factor: 0.2
scheduler_patience: 5
epochs: 100
filter_none: True

metric: "hmean:damage:categorical:f1"
loss_reduce_mode: mean

add_suppl: False
add_tertiary: False
train_repeat: 1

project: building-seg-damage
freeze_encoder_norm: False
freeze_decoder_norm: False
load_weights: False
sync_bn: True
train_patch: False
n_cpus: 10
