---
name: runs
nclasses: 1

data_prefix: pre
batch_size: 6
training_scales: [1.]
training_resolution: 512
eval_resolution: 1024

segmentation_arch: Unet
attention_type: scse


amp_opt_level: O1
aug_prob: 0.30
encoder: efficientnet-b7
loss_weights: {jaccard: 4, focal: 4}
lr: 0.0006 #0.0005
optim: adam
scheduler_factor: 0.2
scheduler_patience: 5
epochs: 120
filter_none: False
mode: null
metric: "building:f1"

dual_input: False

add_suppl: False
add_tertiary: False
train_repeat: 1

project: sky-eye-full
freeze_encoder_norm: False
freeze_decoder_norm: False
load_weights: False
sync_bn: True
train_patch: True
n_cpus: 8
