---
name: deform
nclasses: 1

data_prefix: pre
batch_size: 6
training_scales: [1.]
training_resolution: 512
eval_resolution: 1024

segmentation_arch: Unet
attention_type: scse
#decoder_segmentation_channels: 480
#decoder_pyramid_channels: 256
#decoder_merge_policy: add
#deform_layers: ['s3', 's4', 's5'] # ['s2', 's3', 's4', 's5']
deform_layers: ['layer1', 'layer2', 'layer3'] #, 'layer4']

amp_opt_level: O1
aug_prob: 0.30
encoder: efficientnet-b6
loss_weights: {jaccard: 4, focal: 4}
lr: 0.0005 #0.0005
optim: adam
scheduler_factor: 0.2
scheduler_patience: 5
epochs: 120
filter_none: False
mode: null
metric: "building:f1"

dual_input: False

add_suppl: False
add_tertiary: False
train_repeat: 1

project: sky-eye-full
freeze_encoder_norm: False
freeze_decoder_norm: False
load_weights: False
sync_bn: True
train_patch: True
n_cpus: 4
