--- 
nclasses: 4
data_prefix: post
name: enet7-finetune
batch_size: 1
aug_prob: 0.5
training_scales: [1.,]
loss_weights: {ce: 1}
lr: 0.0000002
optim: adam
scheduler_factor: 0.5
scheduler_patience: 5
epochs: 100
metric: "hmean:damage:categorical:f1"
filter_none: True
class_weight: [1, 3, 2, 2]
loss_reduce_mode: "mean"
min_bbox_visibility: 0.2
pretrain_weights: "wandb/run-20191201_103244-5khkabft/state_dict.pth"
add_suppl: False
train_repeat: 1

amp_opt_level: O0

freeze_backbone_norm: False
freeze_model_norm: True
convert_groupnorm: False

model_params:
    encoder_name: efficientnet-b7
    nclasses: 4
    features: [3,2,1,0]
    out_channels: 256
