--- 
nclasses: 4
data_prefix: post
name: se101
batch_size: 6
aug_prob: 0.5
training_scales: [1,]
loss_weights: {ce: 1}
lr: 0.000002
optim: adam
scheduler_factor: 0.5
scheduler_patience: 5
epochs: 100
metric: "hmean:damage:categorical:f1"
filter_none: True
class_weight: [1, 3, 2, 2]
loss_reduce_mode: "mean"
min_bbox_visibility: 0.2
pretrain_weights: False
add_suppl: False
train_repeat: 1

amp_opt_level: O1

freeze_backbone_norm: False
convert_groupnorm: False

model_params:
    encoder_name: se_resnet101
    nclasses: 4
    features: [3,2,1,0]
    out_channels: 256
