--- 
nclasses: 4
data_prefix: post
run_name: building_damage
segmentation_arch: Linknet
batch_size: 2
amp_opt_level: O1
aug_prob: 0.5
encoder: efficientnet-b7
training_resolution: 1024
training_scales: [0.5, 0.75, 1.]
loss_weights: {ce: 1}
lr: 0.00025
optim: adam
scheduler_factor: 0.5
scheduler_patience: 5
epochs: 100
metric: "hmean:damage:categorical:f1"
mode: categorical
filter_none: True
class_weight: [1, 3, 2, 2]
add_suppl: True
project: building-damage