--- 
train_post: 
    desc: Boolean determining whether to train damage-map component.
    value: false
train_pre:
    desc: Boolean determining whether to train building-localization component.
    value: true
batch_size: 6
amp_opt_level: O1
aug_prob: 0.5
blocks: [2,4]
blocktype: bottleneck
damage_scale_mode: ordinal
dmg_downscale_ratio: 4
encoder: efficientnet-b7
epochs: 100
growth_rate: 1
image_size: 512
loss_weights:
    value: {dice: 1, focal: 4}
lr: 0.0003
n_dmg_classes: 4
optim: adam
post_weight: 1.0
pre_weight: 1.0
scheduler_factor: 0.5
scheduler_patience: 5
segmentation_arch: Linknet
strides: [2,2]
