wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.15
    is_jupyter_run: true
    python_version: 3.7.4
add_suppl:
  desc: null
  value: false
amp_opt_level:
  desc: null
  value: O1
attention:
  desc: null
  value: scse
aug_prob:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 1
data_prefix:
  desc: null
  value: pre
encoder:
  desc: null
  value: efficientnet-b7
epochs:
  desc: null
  value: 100
filter_none:
  desc: null
  value: false
freeze_decoder_norm:
  desc: null
  value: true
freeze_encoder_norm:
  desc: null
  value: true
load_weights:
  desc: null
  value: ./wandb/run-20191114_063404-0udvk80d/state_dict.pth
loss_weights:
  desc: null
  value:
    focal: 4
    jaccard: 1
lr:
  desc: null
  value: 0.0001
metric:
  desc: null
  value: building:f1
mode:
  desc: null
  value: null
nclasses:
  desc: null
  value: 1
optim:
  desc: null
  value: adam
project:
  desc: null
  value: sky-eye-full
scheduler_factor:
  desc: null
  value: 0.5
scheduler_patience:
  desc: null
  value: 5
segmentation_arch:
  desc: null
  value: Unet
train_repeat:
  desc: null
  value: 1
training_resolution:
  desc: null
  value: 1024
training_scales:
  desc: null
  value:
  - 0.75
  - 1
