--- 
nclasses: 4
data_prefix: post
run_name: building_damage
segmentation_arch: Linknet
batch_size: 6
amp_opt_level: O1
aug_prob: 0.5
encoder: efficientnet-b6
training_resolution: 512
loss_weights: {ce: 1}
lr: 0.00025
optim: adam
scheduler_factor: 0.5
scheduler_patience: 5
epochs: 100
metric: "hmean:damage:categorical:f1"
mode: categorical
filter_none: True
class_weight: [1, 6, 3, 3]