---
nclasses: 1
data_prefix: pre
segmentation_arch: Linknet
batch_size: 1
amp_opt_level: O1
aug_prob: 0.5
encoder: efficientnet-b7
training_resolution: 1024
training_scales: [0.75, 1.]
loss_weights: {jaccard: 1, focal: 4}
lr: 0.00005
optim: adam
scheduler_factor: 0.5
scheduler_patience: 5
epochs: 100
filter_none: False
mode: null
metric: "building:f1"
add_suppl: False
train_repeat: 1
project: sky-eye-full
freeze_encoder_norm: True
freeze_decoder_norm: True
load_weights: '../weights/state_dict.pth'